### ISSUE TITLE
Option to select default fiat currency

### ISSUE THREAD

**Issue by vjaykrsna** [SUPEROLEJKAAA/Flow.Launcher.Plugin.BinancePrice#1]
In plugin option give us option to select default currency like USD/INR.

**Comment by SUPEROLEJKAAA** [comment]
Binance does not allow you to get under many fiat currencies. Perhaps a little later I will separately add conversion of USDT to any fiat currency.

**Comment by vjaykrsna** [comment]
yeah i was also talking about direct conversion because binance doesn't has multiple trading pairs for all tokens
maybe we can integrate coinmarketcap api for seamlessly tracking more coins and tokens
