### ISSUE TITLE
i dont know how to install this?

### ISSUE THREAD

**Issue by ham1tcagdas** [SUPEROLEJKAAA/Flow.Launcher.Plugin.BinancePrice#2]
i dont know how to install this?

![image](https://github.com/user-attachments/assets/177a1f82-275e-4d2c-b70b-4a669083da7f)
thats FlowLauncher folder. Where do i put all this files ?
![image](https://github.com/user-attachments/assets/5ccd26c5-f0b7-4152-af9b-50c10d086b0f)

**Comment by SUPEROLEJKAAA** [comment]
You need to go to FlowLauncher settings, go to plugins, and search for write “Binance”, select it there and click “install”. This will be more convenient for you.

**Comment by ham1tcagdas** [comment]
Got it thx.
